@PushIt_HostAddress = http://localhost:5176

POST {{PushIt_HostAddress}}/canvas
Content-Type: application/json

{
    "Name":"placeholder",
    "QuadrosAnotacoes": [ ],
    "CreatedDateTime":"2025-04-22T15:00:00"
}

###

POST {{PushIt_HostAddress}}/canvas/placeholder/quadros
Content-Type: application/json

{
    "id":"IDhere",
    "x":1,
    "y":1,
    "width":33,
    "height":1,
    "text":"placeholder",
    "colour":"#000000"  
}

###

PUT {{PushIt_HostAddress}}/canvas/placeholder/quadros/IDhere
Content-Type: application/json

{
    "x":2121,
    "y":67,
    "width":33,
    "height":1,
    "text":"otherText",
    "colour":"#01450"  
}

###

GET {{PushIt_HostAddress}}/canvas/placeholder/quadros/IDhere11
Accept: application/json

###

GET {{PushIt_HostAddress}}/canvas/placeholder/quadros
Accept: application/json

###[{"TextoInterno":"texto1"},{"TextoInterno":"texto2"},{"TextoInterno":"texto3"}]
###

GET {{PushIt_HostAddress}}/canvas/placeholder
Accept: application/json

###

###DELETE {{PushIt_HostAddress}}/canvas/placeholder

###