###Variáveis para facilitar a estruturação de Requisições
@PushIt_HostAddress = http://localhost:5176
@NomeCanvas = Validação Teste
@ID_Quadro = 1

@ID_QuadroDestino = 1


### Criar Canvas
POST {{PushIt_HostAddress}}/canvas
Content-Type: application/json

{
    "Name":"Validação Teste",
    "CreatedDateTime":"2025-04-22T15:00:00"
}


### Criar Quadro de Anotações em um Canvas
POST {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros
Content-Type: application/json

{
    "id":"1",
    "x":1.0,
    "y":1.0,
    "width":33,
    "height":1,
    "text":"placeholder",
    "colour":"#000000"  
}


### Atualizar um Quadro de Anotações de um Canvas
PUT {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros/{{ID_Quadro}}
Content-Type: application/json

{
    "x":66,
    "y":66,
    "width":66,
    "height":66,
    "text":"66",
    "colour":"#01450"  
}


### Obter um Quadro de Anotações em específico de um Canvas
GET {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros/{{ID_Quadro}}
Accept: application/json


### Obter TODOS os Quadros de Anotações existentes em um Canvas
GET {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros
Accept: application/json


### Deletar um Quadro de Anotações em específico de um Canvas
DELETE {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros/{{ID_Quadro}}


### Obter todos os Dados de um Canvas (incluindo seus Quadros de Anotações)
GET {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}
Accept: application/json


### Obter todos os IDs de Quadros de Anotações que um Quadro de Anotações em específico aponta
GET {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros/{{ID_Quadro}}/conexoes
Accept: application/json

### Criar uma Seta de conexão entre dois quadros de um Canvas
### Inserir no URI o ID do Quadro de onde começa a seta, e inserir no JSON da request o ID para onde a Seta Aponta

POST {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros/{{ID_Quadro}}/conexoes
Content-Type: application/json

{
    "IdQuadroDestino":"1ss"
}


### Deletar uma Seta de conexão
DELETE {{PushIt_HostAddress}}/canvas/{{NomeCanvas}}/quadros/{{ID_Quadro}}/conexoes/{{ID_QuadroDestino}}